### ISSUE TITLE
Provide AppsFlyerID

### ISSUE THREAD

**Issue by drathar** [segment-integrations/analytics-kotlin-appsflyer#13]
Hey team! 👋

I have an AppsFlyer integration set up in a way that I cannot omit the AppsFlyerID from events.
I tried modifying the plugin code so that I can integrate it into all events, but I cannot find a way to do so.
Can you help me with some guidance on how this should be done properly, please?

Thank you in advance!

**Comment by alanjcharles** [comment]
Hi @drathar! In order to streamline the reporting and escalation process internally, we are disabling Github Issues for this repository. If you are still experiencing this issue please send a copy of your report, as well as any other information you might have, to `friends@segment.com`  so we can prioritize it accordingly. Thanks and apologies for the inconvenience!
